---
home: '{{ ansible_env.HOME }}'
theme: powerlevel10k/powerlevel10k
plugins:
  - git
  - autojump
  - thefuck
  - tmux
  - web-search
  - last-working-dir
  - terraform
custom_plugins: 
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
custom_themes:
  - name: powerlevel10k
    repo: https://github.com/romkatv/powerlevel10k.git