---
- name: install homebrew's app
  homebrew: 
    name: '{{ standard_list }}'
    state: present
  ignore_errors: yes

- name: install homebrew cask's app
  homebrew_cask: 
    name: '{{ cask_list }}'
    state: installed
  ignore_errors: yes